# Generated by Django 4.2.11 on 2024-05-14 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserHydration',
            new_name='UserHydrationwoa',
        ),
    ]
