# Generated by Django 4.2.11 on 2024-05-14 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppPages', '0002_rename_userhydration_userhydrationwoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHydration',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hydration_dates', models.JSONField(default=list)),
            ],
        ),
        migrations.DeleteModel(
            name='UserHydrationwoa',
        ),
    ]
